### ISSUE TITLE
每次更新模拟器都出现异常

### ISSUE THREAD

**Issue by dabaowwj** [triwinds/ns-emu-tools#104]
用0.4.5之前的版本都没出现过，而用0.4.6和0.4.7都有这个问题，虽然出现了异常，但是实际上是有更新成功

下载完成
正在解压 ryujinx 文件...
清除旧版 ryujinx 文件...
安装 ryujinx 文件至目录...
出现异常, Traceback (most recent call last):
  File "api\ryujinx_api.py", line 79, in install_ryujinx
  File "module\ryujinx.py", line 88, in install_ryujinx_by_version
  File "module\common.py", line 15, in check_and_install_msvc
  File "utils\common.py", line 111, in find_installed_software
  File "utils\common.py", line 105, in get_installed_software
  File "utils\common.py", line 86, in foo
ValueError: embedded null character
embedded null character

[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/14748719/ns-emu-tools.log)
[aria2.log](https://github.com/triwinds/ns-emu-tools/files/14748725/aria2.log)

**Comment by triwinds** [comment]
试试这个版本： https://github.com/triwinds/ns-emu-tools/actions/runs/8468079555
