### ISSUE TITLE
yuzu检测报错，能否设置版本检测可选？

### ISSUE THREAD

**Issue by yancy5499** [triwinds/ns-emu-tools#108]
众所周知yuzu的github已经404了，但似乎现在每次打开工具都会版本自检
然后报错

报错如下：
出现异常, Traceback (most recent call last):
  File "api\yuzu_api.py", line 99, in get_all_yuzu_release_versions
  File "repository\yuzu.py", line 19, in get_all_yuzu_release_versions
TypeError: string indices must be integers, not 'str'
yuzu 版本信息加载异常.

**Comment by triwinds** [comment]
Fixed in 0.5.0
