### ISSUE TITLE
Windows登陆帐户为中文名时报错，这一点相对021版本是个大BUG。

### ISSUE THREAD

**Issue by hepinjy** [triwinds/ns-emu-tools#11]
检测固件版本报错如下 。现已改回使用021版本
“出现异常, Traceback (most recent call last):
File "api\common_api.py", line 48, in detect_firmware_version
File "module\firmware.py", line 37, in detect_firmware_version
RuntimeError: no firmware files found in path: C:\Users\x90dd\x83f2\AppData\Roaming\yuzu\nand\system\Contents\registered
固件版本检测完成”这里的**x90dd\x83f2**把x改成u就是我win中文帐户名Unicode码

**Comment by triwinds** [comment]
https://github.com/triwinds/ns-emu-tools/actions/runs/3602640475

修了一版，试试看？

**Comment by hepinjy** [comment]
这一版正常了 无报错



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: triwinds ***@***.***&gt;
发送时间: 2022年12月2日 22:51
收件人: triwinds/ns-emu-tools ***@***.***&gt;
抄送: hepinjy ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [triwinds/ns-emu-tools] Windows登陆帐户为中文名时报错，这一点相对021版本是个大BUG。 (Issue #11)





 
https://github.com/triwinds/ns-emu-tools/actions/runs/3602640475
 
修了一版，试试看？
