### ISSUE TITLE
请问现在我一打开就报错怎么办

### ISSUE THREAD

**Issue by twoSkuld** [triwinds/ns-emu-tools#110]
请在描述问题的同时上传 ns-emu-tools.log 这个文件。
如果问题与 aria2 下载有关，请将 aria2.log 这个文件也带上。
(将文件拖拽至输入框内即可)
[ns-emu-tools.log](https://github.com/user-attachments/files/15788842/ns-emu-tools.log)
![image](https://github.com/triwinds/ns-emu-tools/assets/95513243/dea1e682-b98d-4eac-9b48-384fd566dd22)
报错信息如下：
Traceback (most recent call last):
  File "main_devnull.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "main.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "config.py", line 126, in <module>
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by triwinds** [comment]
将 exe 同目录下的 config.json 删掉或者把 exe 换个目录应该就好了
