### ISSUE TITLE
yuzu 最新版本信息加载异常

### ISSUE THREAD

**Issue by 745628409** [triwinds/ns-emu-tools#12]
修改已取消
出现异常, Traceback (most recent call last):
File "api\yuzu_api.py", line 92, in get_all_yuzu_release_versions
File "repository\yuzu.py", line 20, in get_all_yuzu_release_versions
TypeError: string indices must be integers
yuzu 版本信息加载异常.

报错↑

**Comment by 745628409** [comment]
退回v0.2.2倒是没事

**Comment by triwinds** [comment]
可能是你的 ip 被 GitHub block 了，在设置里面将 GitHub api 改成使用 CDN 再试试
