### ISSUE TITLE
aria下载的问题

### ISSUE THREAD

**Issue by Tacrine** [triwinds/ns-emu-tools#21]
报错，代码为1
2023-01-27 18:12:45.135990 [INFO] [rpc_helper.cc:103] Executing RPC method aria2.tellStatus
2023-01-27 18:12:45.136990 [INFO] [AbstractHttpServerResponseCommand.cc:117] CUID#691 - HttpServer: all response transmitted.
2023-01-27 18:12:45.136990 [INFO] [HttpServerResponseCommand.cc:60] CUID#691 - Persist connection.
2023-01-27 18:12:45.136990 [INFO] [HttpServerCommand.cc:272] CUID#690 - Error occurred while reading HTTP request
Exception: [HttpServer.cc:180] errorCode=1 Got EOF from peer.
2023-01-27 18:12:45.136990 [INFO] [HttpServerCommand.cc:272] CUID#691 - Error occurred while reading HTTP request
Exception: [HttpServer.cc:180] errorCode=1 Got EOF from peer.

**Comment by triwinds** [comment]
这个是因为 aria2p 在调用 jsonrpc 时请求头设置有点问题，不是出问题的根本原因。

ns-emu-tools.log 里面找找 info.error_code，这个才是 aria2 下载出问题时返回的 error code，看看这个 error code 写的是什么？

**Comment by Tacrine** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Tacrine** [comment]
2023-01-27 19:32:00.450|ERROR|api.common_response|common_response.py:14|exception_response|下载出错, error_code: 2, error message: Timeout.
Traceback (most recent call last):
  File "api\yuzu_api.py", line 60, in install_yuzu
  File "module\yuzu.py", line 103, in install_yuzu
  File "module\yuzu.py", line 67, in install_ea_yuzu
  File "module\yuzu.py", line 44, in download_yuzu
  File "module\downloader.py", line 93, in download
RuntimeError: 下载出错, error_code: 2, error message: Timeout.
[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/10518380/ns-emu-tools.log)

**Comment by Tacrine** [comment]
2023-01-27 17:41:35.220|ERROR|module.downloader|downloader.py:92|download|info.error_code: 2, error message: Timeout.
2023-01-27 17:41:35.220|ERROR|api.common_response|common_response.py:14|exception_response|下载出错, error_code: 2, error message: Timeout.
Traceback (most recent call last):
  File "api\yuzu_api.py", line 60, in install_yuzu
  File "module\yuzu.py", line 103, in install_yuzu
  File "module\yuzu.py", line 67, in install_ea_yuzu
  File "module\yuzu.py", line 44, in download_yuzu
  File "module\downloader.py", line 93, in download
RuntimeError: 下载出错, error_code: 2, error message: Timeout.
[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/10518388/ns-emu-tools.log)

**Comment by Tacrine** [comment]
这是墙的问题吧

**Comment by Tacrine** [comment]
这是墙的问题吧

**Comment by triwinds** [comment]
有可能，设置里换个下载源或者挂个梯子再试试吧。

**Comment by Tacrine** [comment]
其他下载源都试过了，没用。另外下载源都是cf的cdn，其实也都一样，我挂个梯子试试。

**Comment by triwinds** [comment]
https://ping.chinaz.com/nsarchive.e6ex.com
https://ping.chinaz.com/proxy.zyun.vip

看起来大部分地区访问都是正常的，可能是 dns 给你的 ip 无法访问或者是你的网络有一些限制。
过段时间我试试集成一下 CloudflareST，看看能不能解决这个问题。

**Comment by Tacrine** [comment]
感谢大佬

**Comment by Tacrine** [comment]
我用的是edge浏览器，浏览器自动用电信提供的dns，我手动修改后就好了
