### ISSUE TITLE
检测yuzu版本报错

### ISSUE THREAD

**Issue by Ecc2u** [triwinds/ns-emu-tools#38]
```

正在检测 yuzu 版本...
正在启动 yuzu ...
出现异常, Traceback (most recent call last):
  File "api\yuzu_api.py", line 46, in detect_yuzu_version
  File "module\yuzu.py", line 145, in detect_yuzu_version
  File "sentry_sdk\integrations\stdlib.py", line 211, in sentry_patched_popen_init
  File "subprocess.py", line 971, in __init__
  File "subprocess.py", line 1440, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
检测 yuzu 版本时发生异常

```

**Comment by triwinds** [comment]
你选的目录底下有 yuzu.exe 这个文件吗？

**Comment by Ecc2u** [comment]
![捕获](https://user-images.githubusercontent.com/95345540/230442627-8026f6dc-db29-4b3e-8f3f-73f4177ec5d9.PNG)
路径应该没问题

**Comment by triwinds** [comment]
emmm, 你的系统是禁用了 powershell 吗？

**Comment by triwinds** [comment]
现在 yuzu 版本检测已经不再使用 powershell 了，可以再试一下，如果还有问题再重新打开这个 issue
