### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by RonaldinhoL** [triwinds/ns-emu-tools#44]
2023-05-06 14:55:58.633|INFO|module.network|network.py:200|request_github_api|requesting github api: https://api.github.com/repos/pineappleEA/pineapple-src/releases
2023-05-06 14:55:58.634|INFO|module.network|network.py:177|get_override_url|using new url: https://cfrp.e6ex.com/ghapi/repos/pineappleEA/pineapple-src/releases
2023-05-06 14:55:58.637|DEBUG|requests_cache.policy.actions|actions.py:91|from_request|Cache directives from request headers: CacheDirectives()
2023-05-06 14:55:58.638|DEBUG|requests_cache.policy.actions|actions.py:330|_log_cache_criteria|Pre-read cache checks: Passed
2023-05-06 14:55:58.639|DEBUG|requests_cache.policy.actions|actions.py:205|update_from_cached_response|Post-read cache actions: CacheActions(expire_after=-1)
2023-05-06 14:55:58.641|INFO|config|config.py:129|update_last_open_emu_page|update lastOpenEmuPage to yuzu
2023-05-06 14:55:58.642|INFO|config|config.py:119|dump_config|saving config to F:\Emulator\Switch\NsEmuTools\config.json
2023-05-06 14:56:01.057|INFO|module.network|network.py:200|request_github_api|requesting github api: https://api.github.com/repos/Ryujinx/release-channel-master/releases
2023-05-06 14:56:01.058|INFO|module.network|network.py:177|get_override_url|using new url: https://cfrp.e6ex.com/ghapi/repos/Ryujinx/release-channel-master/releases
2023-05-06 14:56:01.062|DEBUG|requests_cache.policy.actions|actions.py:91|from_request|Cache directives from request headers: CacheDirectives()
2023-05-06 14:56:01.062|DEBUG|requests_cache.policy.actions|actions.py:330|_log_cache_criteria|Pre-read cache checks: Passed
2023-05-06 14:56:01.063|DEBUG|requests_cache.policy.actions|actions.py:205|update_from_cached_response|Post-read cache actions: CacheActions(expire_after=-1, send_request=True)
2023-05-06 14:56:01.068|INFO|config|config.py:129|update_last_open_emu_page|update lastOpenEmuPage to ryujinx
2023-05-06 14:56:01.069|INFO|config|config.py:119|dump_config|saving config to F:\Emulator\Switch\NsEmuTools\config.json
2023-05-06 14:56:01.878|DEBUG|requests_cache.policy.actions|actions.py:253|_update_from_response_headers|Cache directives from response headers: CacheDirectives(max_age=300)
2023-05-06 14:56:01.879|DEBUG|requests_cache.policy.actions|actions.py:330|_log_cache_criteria|Pre-write cache checks: Passed
2023-05-06 14:56:15.702|INFO|module.network|network.py:200|request_github_api|requesting github api: https://api.github.com/repos/pineappleEA/pineapple-src/releases
2023-05-06 14:56:15.703|INFO|module.network|network.py:177|get_override_url|using new url: https://cfrp.e6ex.com/ghapi/repos/pineappleEA/pineapple-src/releases
2023-05-06 14:56:15.706|DEBUG|requests_cache.policy.actions|actions.py:91|from_request|Cache directives from request headers: CacheDirectives()
2023-05-06 14:56:15.707|DEBUG|requests_cache.policy.actions|actions.py:330|_log_cache_criteria|Pre-read cache checks: Passed
2023-05-06 14:56:15.708|DEBUG|requests_cache.policy.actions|actions.py:205|update_from_cached_response|Post-read cache actions: CacheActions(expire_after=-1)
2023-05-06 14:56:15.711|INFO|config|config.py:129|update_last_open_emu_page|update lastOpenEmuPage to yuzu
2023-05-06 14:56:15.711|INFO|config|config.py:119|dump_config|saving config to F:\Emulator\Switch\NsEmuTools\config.json
2023-05-06 14:56:20.246|INFO|api.yuzu_api|yuzu_api.py:89|switch_yuzu_branch|switch yuzu branch to mainline
2023-05-06 14:56:20.247|INFO|config|config.py:119|dump_config|saving config to F:\Emulator\Switch\NsEmuTools\config.json
2023-05-06 14:56:20.257|INFO|module.network|network.py:200|request_github_api|requesting github api: https://api.github.com/repos/yuzu-emu/yuzu-mainline/releases
2023-05-06 14:56:20.258|INFO|module.network|network.py:177|get_override_url|using new url: https://cfrp.e6ex.com/ghapi/repos/yuzu-emu/yuzu-mainline/releases
2023-05-06 14:56:20.261|DEBUG|requests_cache.policy.actions|actions.py:91|from_request|Cache directives from request headers: CacheDirectives()
2023-05-06 14:56:20.262|DEBUG|requests_cache.policy.actions|actions.py:330|_log_cache_criteria|Pre-read cache checks: Passed
2023-05-06 14:56:20.263|DEBUG|requests_cache.policy.actions|actions.py:205|update_from_cached_response|Post-read cache actions: CacheActions(expire_after=-1, send_request=True)
2023-05-06 14:56:21.167|DEBUG|requests_cache.policy.actions|actions.py:253|_update_from_response_headers|Cache directives from response headers: CacheDirectives(max_age=300)
2023-05-06 14:56:21.168|DEBUG|requests_cache.policy.actions|actions.py:330|_log_cache_criteria|Pre-write cache checks: Passed
2023-05-06 14:56:21.439|INFO|api.yuzu_api|yuzu_api.py:89|switch_yuzu_branch|switch yuzu branch to ea
2023-05-06 14:56:21.440|INFO|config|config.py:119|dump_config|saving config to F:\Emulator\Switch\NsEmuTools\config.json
2023-05-06 14:56:21.447|INFO|module.network|network.py:200|request_github_api|requesting github api: https://api.github.com/repos/pineappleEA/pineapple-src/releases
2023-05-06 14:56:21.448|INFO|module.network|network.py:177|get_override_url|using new url: https://cfrp.e6ex.com/ghapi/repos/pineappleEA/pineapple-src/releases
2023-05-06 14:56:21.451|DEBUG|requests_cache.policy.actions|actions.py:91|from_request|Cache directives from request headers: CacheDirectives()
2023-05-06 14:56:21.452|DEBUG|requests_cache.policy.actions|actions.py:330|_log_cache_criteria|Pre-read cache checks: Passed
2023-05-06 14:56:21.453|DEBUG|requests_cache.policy.actions|actions.py:205|update_from_cached_response|Post-read cache actions: CacheActions(expire_after=-1)
2023-05-06 14:56:22.727|INFO|api.yuzu_api|yuzu_api.py:89|switch_yuzu_branch|switch yuzu branch to mainline
2023-05-06 14:56:22.728|INFO|config|config.py:119|dump_config|saving config to F:\Emulator\Switch\NsEmuTools\config.json
2023-05-06 14:56:22.735|INFO|module.network|network.py:200|request_github_api|requesting github api: https://api.github.com/repos/yuzu-emu/yuzu-mainline/releases
2023-05-06 14:56:22.736|INFO|module.network|network.py:177|get_override_url|using new url: https://cfrp.e6ex.com/ghapi/repos/yuzu-emu/yuzu-mainline/releases
2023-05-06 14:56:22.739|DEBUG|requests_cache.policy.actions|actions.py:91|from_request|Cache directives from request headers: CacheDirectives()
2023-05-06 14:56:22.740|DEBUG|requests_cache.policy.actions|actions.py:330|_log_cache_criteria|Pre-read cache checks: Passed
2023-05-06 14:56:22.741|DEBUG|requests_cache.policy.actions|actions.py:205|update_from_cached_response|Post-read cache actions: CacheActions(expire_after=-1)
2023-05-06 14:56:23.402|INFO|api.yuzu_api|yuzu_api.py:89|switch_yuzu_branch|switch yuzu branch to ea
2023-05-06 14:56:23.403|INFO|config|config.py:119|dump_config|saving config to F:\Emulator\Switch\NsEmuTools\config.json
2023-05-06 14:56:23.410|INFO|module.network|network.py:200|request_github_api|requesting github api: https://api.github.com/repos/pineappleEA/pineapple-src/releases
2023-05-06 14:56:23.410|INFO|module.network|network.py:177|get_override_url|using new url: https://cfrp.e6ex.com/ghapi/repos/pineappleEA/pineapple-src/releases
2023-05-06 14:56:23.414|DEBUG|requests_cache.policy.actions|actions.py:91|from_request|Cache directives from request headers: CacheDirectives()
2023-05-06 14:56:23.414|DEBUG|requests_cache.policy.actions|actions.py:330|_log_cache_criteria|Pre-read cache checks: Passed
2023-05-06 14:56:23.416|DEBUG|requests_cache.policy.actions|actions.py:205|update_from_cached_response|Post-read cache actions: CacheActions(expire_after=-1)
2023-05-06 14:56:25.302|DEBUG|module.yuzu|yuzu.py:224|_get_yuzu_data_storage_config|{'use_virtual_sd\\default': 'true', 'use_virtual_sd': 'true', 'nand_directory\\default': 'true', 'nand_directory': 'C:\\\\Users\\\\Ronaldinho\\\\AppData\\\\Roaming\\\\yuzu\\\\nand', 'sdmc_directory\\default': 'true', 'sdmc_directory': 'C:\\\\Users\\\\Ronaldinho\\\\AppData\\\\Roaming\\\\yuzu\\\\sdmc', 'load_directory\\default': 'true', 'load_directory': 'C:\\\\Users\\\\Ronaldinho\\\\AppData\\\\Roaming\\\\yuzu\\\\load', 'dump_directory\\default': 'true', 'dump_directory': 'C:\\\\Users\\\\Ronaldinho\\\\AppData\\\\Roaming\\\\yuzu\\\\dump', 'tas_directory\\default': 'true', 'tas_directory': 'C:\\\\Users\\\\Ronaldinho\\\\AppData\\\\Roaming\\\\yuzu\\\\tas', 'gamecard_inserted\\default': 'true', 'gamecard_inserted': 'false', 'gamecard_current_game\\default': 'true', 'gamecard_current_game': 'false', 'gamecard_path\\default': 'true', 'gamecard_path': ''}
2023-05-06 14:56:25.306|INFO|module.yuzu|yuzu.py:236|get_yuzu_nand_path|use nand path from yuzu config: C:\Users\Ronaldinho\AppData\Roaming\yuzu\nand
2023-05-06 14:56:25.321|INFO|module.firmware|firmware.py:65|find_target_firmware_file|scanning firmware files...
2023-05-06 14:56:45.063|INFO|module.firmware|firmware.py:79|find_target_firmware_file|target firmware file: C:\Users\Ronaldinho\AppData\Roaming\yuzu\nand\system\Contents\registered\d1b29e04b7816088a9aa0c3d6e307578.nca
2023-05-06 14:56:45.065|INFO|module.firmware|firmware.py:86|extract_version|decrypt file: C:\Users\Ronaldinho\AppData\Roaming\yuzu\nand\system\Contents\registered\d1b29e04b7816088a9aa0c3d6e307578.nca
2023-05-06 14:56:45.305|INFO|module.firmware|firmware.py:101|extract_version|firmware version: 16.0.2
2023-05-06 14:56:45.310|INFO|config|config.py:119|dump_config|saving config to F:\Emulator\Switch\NsEmuTools\config.json
2023-05-06 14:56:45.314|INFO|module.network|network.py:200|request_github_api|requesting github api: https://api.github.com/repos/pineappleEA/pineapple-src/releases/tags/EA-3559
2023-05-06 14:56:45.315|INFO|module.network|network.py:177|get_override_url|using new url: https://cfrp.e6ex.com/ghapi/repos/pineappleEA/pineapple-src/releases/tags/EA-3559
2023-05-06 14:56:45.318|DEBUG|requests_cache.policy.actions|actions.py:91|from_request|Cache directives from request headers: CacheDirectives()
2023-05-06 14:56:45.319|DEBUG|requests_cache.policy.actions|actions.py:330|_log_cache_criteria|Pre-read cache checks: Passed
2023-05-06 14:56:45.320|DEBUG|requests_cache.policy.actions|actions.py:205|update_from_cached_response|Post-read cache actions: CacheActions(expire_after=-1)
2023-05-06 14:56:45.321|INFO|module.yuzu|yuzu.py:29|download_yuzu|target yuzu version: 3559
2023-05-06 14:56:45.322|INFO|module.yuzu|yuzu.py:31|download_yuzu|target yuzu path: F:\Emulator\Switch\yuzu-ea
2023-05-06 14:56:45.323|INFO|module.network|network.py:142|get_github_download_url|using new url: https://nsarchive.e6ex.com/gh/pineappleEA/pineapple-src/releases/download/EA-3559/Windows-Yuzu-EA-3559.zip
2023-05-06 14:56:45.323|INFO|module.yuzu|yuzu.py:44|download_yuzu|downloading yuzu from https://nsarchive.e6ex.com/gh/pineappleEA/pineapple-src/releases/download/EA-3559/Windows-Yuzu-EA-3559.zip
2023-05-06 14:56:45.325|INFO|module.network|network.py:96|is_using_proxy|current proxies: {}
2023-05-06 14:56:49.435|INFO|api.common_response|common_response.py:71|connection_error_handler|HTTPConnectionPool(host='127.0.0.1', port=58005): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025A9A1B6410>: Failed to establish a new connection: [Errno 10061] [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
Traceback (most recent call last):
  File "urllib3\connection.py", line 174, in _new_conn
  File "utils\doh.py", line 178, in patched_create_connection
  File "urllib3\util\connection.py", line 95, in create_connection
  File "urllib3\util\connection.py", line 85, in create_connection
  File "gevent\_socketcommon.py", line 607, in connect
ConnectionRefusedError: [Errno 10061] [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 398, in _make_request
  File "urllib3\connection.py", line 244, in request
  File "http\client.py", line 1283, in request
  File "http\client.py", line 1329, in _send_request
  File "http\client.py", line 1278, in endheaders
  File "http\client.py", line 1038, in _send_output
  File "http\client.py", line 976, in send
  File "urllib3\connection.py", line 205, in connect
  File "urllib3\connection.py", line 186, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000025A9A1B6410>: Failed to establish a new connection: [Errno 10061] [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 489, in send
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=58005): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025A9A1B6410>: Failed to establish a new connection: [Errno 10061] [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "api\yuzu_api.py", line 67, in install_yuzu
  File "module\yuzu.py", line 109, in install_yuzu
  File "module\yuzu.py", line 68, in install_ea_yuzu
  File "module\yuzu.py", line 45, in download_yuzu
  File "module\downloader.py", line 77, in download
  File "module\downloader.py", line 99, in _download
  File "aria2p\api.py", line 229, in add_uris
  File "aria2p\client.py", line 485, in add_uri
  File "aria2p\client.py", line 265, in call
  File "aria2p\client.py", line 361, in post
  File "requests\api.py", line 115, in post
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 587, in request
  File "requests\sessions.py", line 701, in send
  File "requests\adapters.py", line 565, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=58005): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025A9A1B6410>: Failed to establish a new connection: [Errno 10061] [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

2023-05-06 14:57:09.498|INFO|module.network|network.py:200|request_github_api|requesting github api: https://api.github.com/repos/triwinds/ns-emu-tools/releases
2023-05-06 14:57:09.499|INFO|module.network|network.py:177|get_override_url|using new url: https://cfrp.e6ex.com/ghapi/repos/triwinds/ns-emu-tools/releases
2023-05-06 14:57:09.502|DEBUG|requests_cache.policy.actions|actions.py:91|from_request|Cache directives from request headers: CacheDirectives()
2023-05-06 14:57:09.503|DEBUG|requests_cache.policy.actions|actions.py:330|_log_cache_criteria|Pre-read cache checks: disabled cache
2023-05-06 14:57:09.504|DEBUG|requests_cache.policy.actions|actions.py:205|update_from_cached_response|Post-read cache actions: CacheActions(expire_after=-1, send_request=True, skip_read=True)
2023-05-06 14:57:10.240|DEBUG|requests_cache.policy.actions|actions.py:253|_update_from_response_headers|Cache directives from response headers: CacheDirectives(max_age=300)
2023-05-06 14:57:10.241|DEBUG|requests_cache.policy.actions|actions.py:330|_log_cache_criteria|Pre-write cache checks: disabled cache
2023-05-06 14:57:10.242|DEBUG|requests_cache.session|session.py:240|_send_and_cache|Skipping cache write for URL: https://cfrp.e6ex.com/ghapi/repos/triwinds/ns-emu-tools/releases

**Comment by RonaldinhoL** [comment]
2023-05-06 14:53:01.046728 [INFO] [Context.cc:179] <<--- --- --- ---
2023-05-06 14:53:01.049725 [INFO] [Context.cc:180]   --- --- --- ---
2023-05-06 14:53:01.049725 [INFO] [Context.cc:181]   --- --- --- --->>
2023-05-06 14:53:01.049725 [INFO] [Context.cc:182] aria2 1.36.0
2023-05-06 14:53:01.049725 [INFO] [Context.cc:183] mingw-w64 8.0.0 (alpha) / gcc 10-win32 20210110
  built by  x86_64-pc-linux-gnu
  targeting x86_64-w64-mingw32
  on        Aug 21 2021 17:37:16
2023-05-06 14:53:01.049725 [INFO] [Context.cc:184] Windows 6.2 (x86_64) (6.2)
2023-05-06 14:53:01.049725 [INFO] [Context.cc:185] zlib/1.2.11 expat/2.4.1 sqlite3/3.36.0 GMP/6.2.1 c-ares/1.17.2 libssh2/1.9.0
2023-05-06 14:53:01.050225 [INFO] [Context.cc:186] Logging started.
2023-05-06 14:53:01.050225 [INFO] [SocketCore.cc:1585] Checking configured addresses
2023-05-06 14:53:01.129228 [INFO] [SocketCore.cc:1649] Not considered: fe80::b549:a1ed:9d59:d3f4%31
2023-05-06 14:53:01.129728 [INFO] [SocketCore.cc:1649] Not considered: 169.254.155.90
2023-05-06 14:53:01.129728 [INFO] [SocketCore.cc:1649] Not considered: fe80::984d:66dc:91ae:7639%30
2023-05-06 14:53:01.129728 [INFO] [SocketCore.cc:1649] Not considered: 169.254.31.67
2023-05-06 14:53:01.129728 [INFO] [SocketCore.cc:1649] Not considered: fe80::e6f0:3a1:f414:1172%113
2023-05-06 14:53:01.129728 [INFO] [SocketCore.cc:1646] Found configured address: 172.21.128.1
2023-05-06 14:53:01.129728 [INFO] [SocketCore.cc:1649] Not considered: fe80::5ae7:99dc:81f5:7fc5%12
2023-05-06 14:53:01.129728 [INFO] [SocketCore.cc:1649] Not considered: 169.254.37.40
2023-05-06 14:53:01.129728 [INFO] [SocketCore.cc:1649] Not considered: fe80::427c:c35a:eb5a:c195%8
2023-05-06 14:53:01.129728 [INFO] [SocketCore.cc:1649] Not considered: 169.254.59.245
2023-05-06 14:53:01.129728 [INFO] [SocketCore.cc:1649] Not considered: fe80::454b:6f42:612f:996e%5
2023-05-06 14:53:01.129728 [INFO] [SocketCore.cc:1649] Not considered: 169.254.213.192
2023-05-06 14:53:01.129728 [INFO] [SocketCore.cc:1649] Not considered: fe80::e6d4:7e09:a6bc:809%18
2023-05-06 14:53:01.129728 [INFO] [SocketCore.cc:1646] Found configured address: 192.168.31.77
2023-05-06 14:53:01.129728 [INFO] [SocketCore.cc:1649] Not considered: fe80::d1bd:a326:c66c:b5dc%22
2023-05-06 14:53:01.130226 [INFO] [SocketCore.cc:1646] Found configured address: 192.168.162.1
2023-05-06 14:53:01.130226 [INFO] [SocketCore.cc:1649] Not considered: fe80::2e31:810d:5a17:ad75%16
2023-05-06 14:53:01.130226 [INFO] [SocketCore.cc:1646] Found configured address: 192.168.191.1
2023-05-06 14:53:01.130226 [INFO] [SocketCore.cc:1649] Not considered: fe80::2365:883:4d98:3bd8%9
2023-05-06 14:53:01.130226 [INFO] [SocketCore.cc:1649] Not considered: 169.254.163.97
2023-05-06 14:53:01.130226 [INFO] [SocketCore.cc:1649] Not considered: ::1
2023-05-06 14:53:01.130226 [INFO] [SocketCore.cc:1649] Not considered: 127.0.0.1
2023-05-06 14:53:01.130226 [INFO] [SocketCore.cc:1649] Not considered: fe80::cc8c:bbd4:fbdb:b5b9%21
2023-05-06 14:53:01.130226 [INFO] [SocketCore.cc:1646] Found configured address: 172.20.128.1
2023-05-06 14:53:01.130226 [INFO] [SocketCore.cc:1649] Not considered: fe80::f7f6:a69a:5db:d937%60
2023-05-06 14:53:01.130226 [INFO] [SocketCore.cc:1646] Found configured address: 172.18.80.1
2023-05-06 14:53:01.130226 [INFO] [SocketCore.cc:1649] Not considered: fe80::e28c:9691:22b2:b65a%79
2023-05-06 14:53:01.130226 [INFO] [SocketCore.cc:1646] Found configured address: 172.18.208.1
2023-05-06 14:53:01.130226 [INFO] [SocketCore.cc:1649] Not considered: fe80::4575:e3e2:5ac8:7bc5%85
2023-05-06 14:53:01.130226 [INFO] [SocketCore.cc:1646] Found configured address: 172.19.240.1
2023-05-06 14:53:01.130226 [INFO] [SocketCore.cc:1649] Not considered: fe80::466b:5932:ca7:8663%99
2023-05-06 14:53:01.130226 [INFO] [SocketCore.cc:1646] Found configured address: 172.23.112.1
2023-05-06 14:53:01.130226 [INFO] [SocketCore.cc:1649] Not considered: fe80::4b1e:98ad:617e:e92d%105
2023-05-06 14:53:01.130226 [INFO] [SocketCore.cc:1646] Found configured address: 172.18.112.1
2023-05-06 14:53:01.130226 [INFO] [SocketCore.cc:1656] IPv4 configured=1, IPv6 configured=0
2023-05-06 14:53:01.165234 [ERROR] [HttpListenCommand.cc:112] IPv4 RPC: failed to bind TCP port 58005
Exception: [SocketCore.cc:312] errorCode=1 Failed to bind a socket, cause: An attempt was made to access a socket in a way forbidden by its access permissions.

2023-05-06 14:53:01.165234 [ERROR] [MultiUrlRequestInfo.cc:297] Exception caught
Exception: [DownloadEngineFactory.cc:219] errorCode=1 Failed to setup RPC server.

**Comment by RonaldinhoL** [comment]
看起来是 aria2 绑定端口失败了导致python那边连接不了

**Comment by triwinds** [comment]
嗯，看起来是端口绑定失败，但看不出来具体是什么原因...
可以试试重启一下程序，这样会随机另一个端口来启动 aria2，如果能正常启动的话应该是端口被占用了，如果还是不能那就要检查一下你是不是禁用了相关的网络权限了

**Comment by triwinds** [comment]
Fixed in 0.3.9
