### ISSUE TITLE
检测 Ryujinx 版本时发生异常

### ISSUE THREAD

**Issue by EGIONL** [triwinds/ns-emu-tools#55]
正在检测 Ryujinx 版本...
关闭 Ryujinx 进程 [18896]
出现异常, Traceback (most recent call last):
  File "psutil\_pswindows.py", line 694, in wrapper
  File "psutil\_pswindows.py", line 878, in kill
PermissionError: [WinError 5] 拒绝访问。: '(originated from OpenProcess)'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "api\ryujinx_api.py", line 58, in detect_ryujinx_version
  File "module\ryujinx.py", line 195, in detect_ryujinx_version
  File "module\ryujinx.py", line 136, in kill_all_ryujinx_instance
  File "psutil\__init__.py", line 278, in wrapper
  File "psutil\__init__.py", line 1250, in kill
  File "psutil\_pswindows.py", line 696, in wrapper
psutil.AccessDenied: (pid=18896, name='Ryujinx.Ava.exe')
检测 Ryujinx 版本时发生异常
[ns-emu-tools.log](https://github.com/triwinds/ns-emu-tools/files/11469185/ns-emu-tools.log)

**Comment by triwinds** [comment]
这是因为程序无法关闭你当前的 Ryujinx 进程。你可以试试在任务管理器里面关掉 Ryujinx ，也可以重启系统之后再试试。

**Comment by EGIONL** [comment]
你好，请问你能帮我删除这个issue吗？
