### ISSUE TITLE
您好，请问0.20版本出现  出现异常, Traceback (most recent call last):是怎么回事呀？

### ISSUE THREAD

**Issue by AyanamiRei21** [triwinds/ns-emu-tools#6]
出现异常, 
Traceback (most recent call last):
File "urllib3\connectionpool.py", line 703, in urlopen
File "urllib3\connectionpool.py", line 449, in _make_request
File "<string>", line 3, in raise_from
File "urllib3\connectionpool.py", line 444, in _make_request
File "http\client.py", line 1374, in getresponse
File "http\client.py", line 318, in begin
File "http\client.py", line 287, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "requests\adapters.py", line 489, in send
File "urllib3\connectionpool.py", line 787, in urlopen
File "urllib3\util\retry.py", line 550, in increment
File "urllib3\packages\six.py", line 769, in reraise
File "urllib3\connectionpool.py", line 703, in urlopen
File "urllib3\connectionpool.py", line 449, in _make_request
File "<string>", line 3, in raise_from
File "urllib3\connectionpool.py", line 444, in _make_request
File "http\client.py", line 1374, in getresponse
File "http\client.py", line 318, in begin
File "http\client.py", line 287, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "api\yuzu_api.py", line 92, in get_all_yuzu_release_versions
File "repository\yuzu.py", line 18, in get_all_yuzu_release_versions
File "requests\sessions.py", line 600, in get
File "requests_cache\session.py", line 115, in request
File "requests_cache\session.py", line 189, in _send_and_cache
File "requests\sessions.py", line 723, in send
File "requests\sessions.py", line 723, in <listcomp>
File "requests\sessions.py", line 266, in resolve_redirects
File "requests_cache\session.py", line 147, in send
File "requests_cache\session.py", line 189, in _send_and_cache
File "requests\sessions.py", line 701, in send
File "requests\adapters.py", line 547, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
yuzu 版本信息加载异常.

请问出现这个提示是什么原因呢。无论是console还是普通版本都提示异常。。是因为网络问题么。系统win11 22621.819

**Comment by triwinds** [comment]
是的，GitHub api 被你的宽带运营商屏蔽了，可以将你的代理软件设置成系统代理模式，或者在设置里面将 GitHub api 改成使用 CDN
