### ISSUE TITLE
更新yuzu模拟器出现异常

### ISSUE THREAD

**Issue by lifein2** [triwinds/ns-emu-tools#66]
正在解压 yuzu 文件...
安装 yuzu 文件至目录...
关闭 yuzu 进程 [13548]
出现异常, Traceback (most recent call last):
  File "psutil\_pswindows.py", line 694, in wrapper
  File "psutil\_pswindows.py", line 878, in kill
PermissionError: [WinError 5] 拒绝访问。: '(originated from OpenProcess)'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "api\yuzu_api.py", line 67, in install_yuzu
  File "module\yuzu.py", line 102, in install_yuzu
  File "module\yuzu.py", line 64, in install_ea_yuzu
  File "module\yuzu.py", line 86, in copy_back_yuzu_files
  File "module\yuzu.py", line 182, in kill_all_yuzu_instance
  File "psutil\__init__.py", line 278, in wrapper
  File "psutil\__init__.py", line 1250, in kill
  File "psutil\_pswindows.py", line 696, in wrapper
psutil.AccessDenied: (pid=13548, name='yuzu.exe')
(pid=13548, name='yuzu.exe')
更新的是3601版本的yuzu

**Comment by triwinds** [comment]
启动中的 yuzu 进程关不掉，试试手动关掉它再更新或者重启一下系统

**Comment by lifein2** [comment]
没有启动yuzu，安装更新后依然报错，重启之后也一样

**Comment by triwinds** [comment]
emmm... 这就有点奇怪了
先试试这个吧，这个版本不会去尝试关闭启动中的模拟器了：
https://github.com/triwinds/ns-emu-tools/actions/runs/5047992254

**Comment by wkai010** [comment]
我也是同样的问题，求解。

正在获取 yuzu 版本信息...
开始下载 yuzu...
使用 GitHub 镜像: [美国 Cloudflare CDN] - 该公益加速源由 [饭太硬] 提供
如果遇到下载失败或卡住的问题, 可以尝试在设置中换个下载源, 如果还是不行就挂个梯子
如果你的网络支持 IPv6, 也可以尝试在设置中允许 aria2 使用 IPv6, 看看能不能解决问题
下载速度: 0.00 B/s, 0.00 B/0.00 B
文件已存在, 跳过下载.
正在解压 yuzu 文件...
安装 yuzu 文件至目录...
关闭 yuzu 进程 [12112]
出现异常, Traceback (most recent call last):
  File "psutil\_pswindows.py", line 694, in wrapper
  File "psutil\_pswindows.py", line 878, in kill
PermissionError: [WinError 5] 拒绝访问。: '(originated from OpenProcess)'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "api\yuzu_api.py", line 67, in install_yuzu
  File "module\yuzu.py", line 102, in install_yuzu
  File "module\yuzu.py", line 64, in install_ea_yuzu
  File "module\yuzu.py", line 86, in copy_back_yuzu_files
  File "module\yuzu.py", line 182, in kill_all_yuzu_instance
  File "psutil\__init__.py", line 278, in wrapper
  File "psutil\__init__.py", line 1250, in kill
  File "psutil\_pswindows.py", line 696, in wrapper
psutil.AccessDenied: (pid=12112, name='yuzu.exe')
(pid=12112, name='yuzu.exe')

**Comment by triwinds** [comment]
@wkai010  那就先试试重启或者上面的那个 ci build 的版本

**Comment by triwinds** [comment]
相关修改已经合并入 0.4.1，如果还有问题的话再重新打开这个 issue
