### ISSUE TITLE
0.19-0.20版本都提示 yuzu 版本信息加载异常. 但0.18版本及以下可用。请问是什么问题。

### ISSUE THREAD

**Issue by AyanamiRei21** [triwinds/ns-emu-tools#7]
出现异常, Traceback (most recent call last):
File "requests\models.py", line 971, in json
File "json\__init__.py", line 346, in loads
File "json\decoder.py", line 337, in decode
File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "api\yuzu_api.py", line 92, in get_all_yuzu_release_versions
File "repository\yuzu.py", line 19, in get_all_yuzu_release_versions
File "requests\models.py", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
yuzu 版本信息加载异常.

**Comment by triwinds** [comment]
把目录下的 http_cache.sqlite 删掉再试试呢？

**Comment by AyanamiRei21** [comment]
> 把目录下的 http_cache.sqlite 删掉再试试呢？

问题依旧。系统版本win11 22621.819. 删除http_cache.sqlite后以管理员方式运行，依然提示有问题。始终无法显示最新的yuzu版本。查看log如下

Traceback (most recent call last):
  File "api\yuzu_api.py", line 92, in get_all_yuzu_release_versions
  File "repository\yuzu.py", line 19, in get_all_yuzu_release_versions
  File "requests\models.py", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-11-20 22:35:07.725|DEBUG|geventwebsocket.handler|websocket.py:368|close|Closed WebSocket
2022-11-20 22:35:07.725|DEBUG|geventwebsocket.handler|websocket.py:366|close|Failed to write closing frame -> closing socket
2022-11-20 22:35:07.726|DEBUG|geventwebsocket.handler|websocket.py:368|close|Closed WebSocket
2022-11-21 07:24:30.534|DEBUG|requests_cache.backends|__init__.py:76|init_backend|Initializing backend: None http_cache
2022-11-21 07:24:30.534|DEBUG|requests_cache.backends.base|base.py:319|__init__|Initializing SQLitePickleDict with serializer: <requests_cache.serializers.pipeline.SerializerPipeline object at 0x000002408F3F19F0>
2022-11-21 07:24:30.534|DEBUG|requests_cache.backends.sqlite|sqlite.py:167|connection|Opening connection to E:\Spiele\游戏相关软件与备份\Nintendo Switch\NsEmuTools-console\http_cache.sqlite:responses
2022-11-21 07:24:30.550|DEBUG|requests_cache.backends.base|base.py:319|__init__|Initializing SQLiteDict with serializer: <requests_cache.serializers.pipeline.SerializerPipeline object at 0x000002408F3F19F0>
2022-11-21 07:24:30.550|DEBUG|requests_cache.backends.sqlite|sqlite.py:167|connection|Opening connection to E:\Spiele\游戏相关软件与备份\Nintendo Switch\NsEmuTools-console\http_cache.sqlite:redirects
2022-11-21 07:24:30.644|INFO|ui|ui.py:45|main|eel init starting...
2022-11-21 07:24:31.300|INFO|ui|ui.py:47|main|eel init finished.
2022-11-21 07:24:33.924|DEBUG|geventwebsocket.handler|handler.py:68|run_application|Initializing WebSocket
2022-11-21 07:24:33.924|DEBUG|geventwebsocket.handler|handler.py:100|upgrade_websocket|Validating WebSocket request
2022-11-21 07:24:33.925|INFO|geventwebsocket.handler|handler.py:242|log_request|127.0.0.1 - - [2022-11-21 07:24:33] "GET /index.html HTTP/1.1" 200 974 0.001000
2022-11-21 07:24:33.949|DEBUG|geventwebsocket.handler|handler.py:68|run_application|Initializing WebSocket
2022-11-21 07:24:33.949|DEBUG|geventwebsocket.handler|handler.py:100|upgrade_websocket|Validating WebSocket request
2022-11-21 07:24:33.950|INFO|geventwebsocket.handler|handler.py:242|log_request|127.0.0.1 - - [2022-11-21 07:24:33] "GET /eel.js HTTP/1.1" 200 6770 0.001000
2022-11-21 07:24:33.952|DEBUG|geventwebsocket.handler|handler.py:68|run_application|Initializing WebSocket
2022-11-21 07:24:33.952|DEBUG|geventwebsocket.handler|handler.py:100|upgrade_websocket|Validating WebSocket request
2022-11-21 07:24:33.954|INFO|geventwebsocket.handler|handler.py:242|log_request|127.0.0.1 - - [2022-11-21 07:24:33] "GET /js/chunk-vendors.ae130549.js HTTP/1.1" 200 325516 0.002001
2022-11-21 07:24:33.955|DEBUG|geventwebsocket.handler|handler.py:68|run_application|Initializing WebSocket
2022-11-21 07:24:33.956|DEBUG|geventwebsocket.handler|handler.py:100|upgrade_websocket|Validating WebSocket request
2022-11-21 07:24:33.957|INFO|geventwebsocket.handler|handler.py:242|log_request|127.0.0.1 - - [2022-11-21 07:24:33] "GET /css/app.8d790b51.css HTTP/1.1" 200 718 0.002003
2022-11-21 07:24:33.958|DEBUG|geventwebsocket.handler|handler.py:68|run_application|Initializing WebSocket
2022-11-21 07:24:33.958|DEBUG|geventwebsocket.handler|handler.py:100|upgrade_websocket|Validating WebSocket request
2022-11-21 07:24:33.961|INFO|geventwebsocket.handler|handler.py:242|log_request|127.0.0.1 - - [2022-11-21 07:24:33] "GET /css/chunk-vendors.253731fa.css HTTP/1.1" 200 701202 0.003002
2022-11-21 07:24:34.032|DEBUG|geventwebsocket.handler|handler.py:68|run_application|Initializing WebSocket
2022-11-21 07:24:34.032|DEBUG|geventwebsocket.handler|handler.py:100|upgrade_websocket|Validating WebSocket request
2022-11-21 07:24:34.033|INFO|geventwebsocket.handler|handler.py:242|log_request|127.0.0.1 - - [2022-11-21 07:24:34] "GET /js/app.15c4b4fe.js HTTP/1.1" 200 118422 0.002001
2022-11-21 07:24:34.212|DEBUG|geventwebsocket.handler|handler.py:68|run_application|Initializing WebSocket
2022-11-21 07:24:34.213|DEBUG|geventwebsocket.handler|handler.py:100|upgrade_websocket|Validating WebSocket request
2022-11-21 07:24:34.214|INFO|geventwebsocket.handler|handler.py:242|log_request|127.0.0.1 - - [2022-11-21 07:24:34] "GET /favicon.ico HTTP/1.1" 200 17158 0.002001
2022-11-21 07:24:34.470|DEBUG|geventwebsocket.handler|handler.py:68|run_application|Initializing WebSocket
2022-11-21 07:24:34.471|DEBUG|geventwebsocket.handler|handler.py:100|upgrade_websocket|Validating WebSocket request
2022-11-21 07:24:34.471|DEBUG|geventwebsocket.handler|handler.py:151|upgrade_connection|Attempting to upgrade connection
2022-11-21 07:24:34.472|DEBUG|geventwebsocket.handler|handler.py:230|upgrade_connection|WebSocket request accepted, switching protocols
2022-11-21 07:24:34.474|INFO|utils.network|network.py:74|get_finial_url_with_mode|using origin url: https://api.github.com/repos/triwinds/ns-emu-tools/releases
2022-11-21 07:24:34.476|DEBUG|requests_cache.policy.actions|actions.py:85|from_request|Cache directives from request headers: {}
2022-11-21 07:24:34.477|INFO|utils.network|network.py:33|is_using_proxy|current proxies: {}
2022-11-21 07:24:34.477|INFO|utils.network|network.py:90|get_override_url|using new url: https://nsarchive.e6ex.com/nsfrp/
2022-11-21 07:24:34.478|DEBUG|requests_cache.policy.actions|actions.py:85|from_request|Cache directives from request headers: {}
2022-11-21 07:24:34.490|INFO|utils.network|network.py:74|get_finial_url_with_mode|using origin url: https://api.github.com/repos/pineappleEA/pineapple-src/releases
2022-11-21 07:24:34.492|DEBUG|requests_cache.policy.actions|actions.py:85|from_request|Cache directives from request headers: {}
2022-11-21 07:24:34.493|INFO|config|config.py:127|update_last_open_emu_page|update lastOpenEmuPage to yuzu
2022-11-21 07:24:34.493|INFO|config|config.py:87|dump_config|saving config to E:\Spiele\游戏相关软件与备份\Nintendo Switch\NsEmuTools-console\config.json
2022-11-21 07:24:35.090|DEBUG|requests_cache.session|session.py:173|_is_cacheable|Pre-cache checks for response from https://nsarchive.e6ex.com/nsfrp/: {'disabled cache': True, 'disabled method': False, 'disabled status': False, 'disabled by filter': False, 'disabled by headers or expiration params': False}
2022-11-21 07:24:35.090|DEBUG|requests_cache.session|session.py:197|_send_and_cache|Skipping cache write for URL: https://nsarchive.e6ex.com/nsfrp/
2022-11-21 07:24:35.174|DEBUG|requests_cache.policy.actions|actions.py:85|from_request|Cache directives from request headers: {}
2022-11-21 07:24:35.223|DEBUG|requests_cache.policy.actions|actions.py:85|from_request|Cache directives from request headers: {}
2022-11-21 07:24:35.863|DEBUG|requests_cache.session|session.py:173|_is_cacheable|Pre-cache checks for response from https://github.com/repos/pineappleEA/pineapple-src/releases: {'disabled cache': True, 'disabled method': False, 'disabled status': True, 'disabled by filter': False, 'disabled by headers or expiration params': False}
2022-11-21 07:24:35.863|DEBUG|requests_cache.session|session.py:197|_send_and_cache|Skipping cache write for URL: https://github.com/repos/pineappleEA/pineapple-src/releases
2022-11-21 07:24:35.863|DEBUG|requests_cache.session|session.py:173|_is_cacheable|Pre-cache checks for response from https://github.com/repos/pineappleEA/pineapple-src/releases: {'disabled cache': True, 'disabled method': False, 'disabled status': True, 'disabled by filter': False, 'disabled by headers or expiration params': False}
2022-11-21 07:24:35.863|DEBUG|requests_cache.session|session.py:197|_send_and_cache|Skipping cache write for URL: https://api.github.com/repos/pineappleEA/pineapple-src/releases
2022-11-21 07:24:35.863|ERROR|api.common_response|common_response.py:14|exception_response|Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "requests\models.py", line 971, in json
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "api\yuzu_api.py", line 92, in get_all_yuzu_release_versions
  File "repository\yuzu.py", line 19, in get_all_yuzu_release_versions
  File "requests\models.py", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022-11-21 07:24:35.902|DEBUG|requests_cache.session|session.py:173|_is_cacheable|Pre-cache checks for response from https://github.com/repos/triwinds/ns-emu-tools/releases: {'disabled cache': True, 'disabled method': False, 'disabled status': True, 'disabled by filter': False, 'disabled by headers or expiration params': False}
2022-11-21 07:24:35.902|DEBUG|requests_cache.session|session.py:197|_send_and_cache|Skipping cache write for URL: https://github.com/repos/triwinds/ns-emu-tools/releases
2022-11-21 07:24:35.902|DEBUG|requests_cache.session|session.py:173|_is_cacheable|Pre-cache checks for response from https://github.com/repos/triwinds/ns-emu-tools/releases: {'disabled cache': True, 'disabled method': False, 'disabled status': True, 'disabled by filter': False, 'disabled by headers or expiration params': False}
2022-11-21 07:24:35.902|DEBUG|requests_cache.session|session.py:197|_send_and_cache|Skipping cache write for URL: https://api.github.com/repos/triwinds/ns-emu-tools/releases
2022-11-21 07:24:54.608|DEBUG|geventwebsocket.handler|websocket.py:368|close|Closed WebSocket
2022-11-21 07:24:54.608|DEBUG|geventwebsocket.handler|websocket.py:366|close|Failed to write closing frame -> closing socket
2022-11-21 07:24:54.609|DEBUG|geventwebsocket.handler|websocket.py:368|close|Closed WebSocket
2022-11-21 07:25:06.701|DEBUG|requests_cache.backends|__init__.py:76|init_backend|Initializing backend: None http_cache
2022-11-21 07:25:06.701|DEBUG|requests_cache.backends.base|base.py:319|__init__|Initializing SQLitePickleDict with serializer: <requests_cache.serializers.pipeline.SerializerPipeline object at 0x0000023B4812DB10>
2022-11-21 07:25:06.701|DEBUG|requests_cache.backends.sqlite|sqlite.py:167|connection|Opening connection to E:\Spiele\游戏相关软件与备份\Nintendo Switch\NsEmuTools-console\http_cache.sqlite:responses
2022-11-21 07:25:06.701|DEBUG|requests_cache.backends.base|base.py:319|__init__|Initializing SQLiteDict with serializer: <requests_cache.serializers.pipeline.SerializerPipeline object at 0x0000023B4812DB10>
2022-11-21 07:25:06.701|DEBUG|requests_cache.backends.sqlite|sqlite.py:167|connection|Opening connection to E:\Spiele\游戏相关软件与备份\Nintendo Switch\NsEmuTools-console\http_cache.sqlite:redirects
2022-11-21 07:25:06.794|INFO|ui|ui.py:45|main|eel init starting...
2022-11-21 07:25:07.388|INFO|ui|ui.py:47|main|eel init finished.
2022-11-21 07:25:10.042|DEBUG|geventwebsocket.handler|handler.py:68|run_application|Initializing WebSocket
2022-11-21 07:25:10.042|DEBUG|geventwebsocket.handler|handler.py:100|upgrade_websocket|Validating WebSocket request
2022-11-21 07:25:10.043|INFO|geventwebsocket.handler|handler.py:242|log_request|127.0.0.1 - - [2022-11-21 07:25:10] "GET /index.html HTTP/1.1" 200 974 0.001001
2022-11-21 07:25:10.063|DEBUG|geventwebsocket.handler|handler.py:68|run_application|Initializing WebSocket
2022-11-21 07:25:10.063|DEBUG|geventwebsocket.handler|handler.py:100|upgrade_websocket|Validating WebSocket request
2022-11-21 07:25:10.064|INFO|geventwebsocket.handler|handler.py:242|log_request|127.0.0.1 - - [2022-11-21 07:25:10] "GET /eel.js HTTP/1.1" 200 6770 0.001002
2022-11-21 07:25:10.064|DEBUG|geventwebsocket.handler|handler.py:68|run_application|Initializing WebSocket
2022-11-21 07:25:10.065|DEBUG|geventwebsocket.handler|handler.py:100|upgrade_websocket|Validating WebSocket request
2022-11-21 07:25:10.067|INFO|geventwebsocket.handler|handler.py:242|log_request|127.0.0.1 - - [2022-11-21 07:25:10] "GET /js/chunk-vendors.ae130549.js HTTP/1.1" 200 325516 0.003006
2022-11-21 07:25:10.068|DEBUG|geventwebsocket.handler|handler.py:68|run_application|Initializing WebSocket
2022-11-21 07:25:10.068|DEBUG|geventwebsocket.handler|handler.py:100|upgrade_websocket|Validating WebSocket request
2022-11-21 07:25:10.069|INFO|geventwebsocket.handler|handler.py:242|log_request|127.0.0.1 - - [2022-11-21 07:25:10] "GET /css/app.8d790b51.css HTTP/1.1" 200 718 0.001000
2022-11-21 07:25:10.070|DEBUG|geventwebsocket.handler|handler.py:68|run_application|Initializing WebSocket
2022-11-21 07:25:10.070|DEBUG|geventwebsocket.handler|handler.py:100|upgrade_websocket|Validating WebSocket request
2022-11-21 07:25:10.080|INFO|geventwebsocket.handler|handler.py:242|log_request|127.0.0.1 - - [2022-11-21 07:25:10] "GET /css/chunk-vendors.253731fa.css HTTP/1.1" 200 701202 0.010007
2022-11-21 07:25:10.123|DEBUG|geventwebsocket.handler|handler.py:68|run_application|Initializing WebSocket
2022-11-21 07:25:10.123|DEBUG|geventwebsocket.handler|handler.py:100|upgrade_websocket|Validating WebSocket request
2022-11-21 07:25:10.124|INFO|geventwebsocket.handler|handler.py:242|log_request|127.0.0.1 - - [2022-11-21 07:25:10] "GET /js/app.15c4b4fe.js HTTP/1.1" 200 118422 0.001004
2022-11-21 07:25:10.286|DEBUG|geventwebsocket.handler|handler.py:68|run_application|Initializing WebSocket
2022-11-21 07:25:10.286|DEBUG|geventwebsocket.handler|handler.py:100|upgrade_websocket|Validating WebSocket request
2022-11-21 07:25:10.287|INFO|geventwebsocket.handler|handler.py:242|log_request|127.0.0.1 - - [2022-11-21 07:25:10] "GET /favicon.ico HTTP/1.1" 200 17158 0.001002
2022-11-21 07:25:10.565|DEBUG|geventwebsocket.handler|handler.py:68|run_application|Initializing WebSocket
2022-11-21 07:25:10.566|DEBUG|geventwebsocket.handler|handler.py:100|upgrade_websocket|Validating WebSocket request
2022-11-21 07:25:10.566|DEBUG|geventwebsocket.handler|handler.py:151|upgrade_connection|Attempting to upgrade connection
2022-11-21 07:25:10.566|DEBUG|geventwebsocket.handler|handler.py:230|upgrade_connection|WebSocket request accepted, switching protocols
2022-11-21 07:25:10.568|INFO|utils.network|network.py:74|get_finial_url_with_mode|using origin url: https://api.github.com/repos/triwinds/ns-emu-tools/releases
2022-11-21 07:25:10.570|DEBUG|requests_cache.policy.actions|actions.py:85|from_request|Cache directives from request headers: {}
2022-11-21 07:25:10.571|INFO|utils.network|network.py:33|is_using_proxy|current proxies: {}
2022-11-21 07:25:10.571|INFO|utils.network|network.py:90|get_override_url|using new url: https://nsarchive.e6ex.com/nsfrp/
2022-11-21 07:25:10.572|DEBUG|requests_cache.policy.actions|actions.py:85|from_request|Cache directives from request headers: {}
2022-11-21 07:25:10.583|INFO|utils.network|network.py:74|get_finial_url_with_mode|using origin url: https://api.github.com/repos/pineappleEA/pineapple-src/releases
2022-11-21 07:25:10.584|DEBUG|requests_cache.policy.actions|actions.py:85|from_request|Cache directives from request headers: {}
2022-11-21 07:25:10.585|INFO|config|config.py:127|update_last_open_emu_page|update lastOpenEmuPage to yuzu
2022-11-21 07:25:10.585|INFO|config|config.py:87|dump_config|saving config to E:\Spiele\游戏相关软件与备份\Nintendo Switch\NsEmuTools-console\config.json
2022-11-21 07:25:11.249|DEBUG|requests_cache.policy.actions|actions.py:85|from_request|Cache directives from request headers: {}
2022-11-21 07:25:11.293|DEBUG|requests_cache.session|session.py:173|_is_cacheable|Pre-cache checks for response from https://nsarchive.e6ex.com/nsfrp/: {'disabled cache': True, 'disabled method': False, 'disabled status': False, 'disabled by filter': False, 'disabled by headers or expiration params': False}
2022-11-21 07:25:11.293|DEBUG|requests_cache.session|session.py:197|_send_and_cache|Skipping cache write for URL: https://nsarchive.e6ex.com/nsfrp/
2022-11-21 07:25:11.347|DEBUG|requests_cache.policy.actions|actions.py:85|from_request|Cache directives from request headers: {}
2022-11-21 07:25:50.878|ERROR|api.common_response|common_response.py:14|exception_response|('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 449, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3\connectionpool.py", line 444, in _make_request
  File "http\client.py", line 1374, in getresponse
  File "http\client.py", line 318, in begin
  File "http\client.py", line 287, in _read_status
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 489, in send
  File "urllib3\connectionpool.py", line 787, in urlopen
  File "urllib3\util\retry.py", line 550, in increment
  File "urllib3\packages\six.py", line 769, in reraise
  File "urllib3\connectionpool.py", line 703, in urlopen
  File "urllib3\connectionpool.py", line 449, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3\connectionpool.py", line 444, in _make_request
  File "http\client.py", line 1374, in getresponse
  File "http\client.py", line 318, in begin
  File "http\client.py", line 287, in _read_status
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "api\yuzu_api.py", line 92, in get_all_yuzu_release_versions
  File "repository\yuzu.py", line 18, in get_all_yuzu_release_versions
  File "requests\sessions.py", line 600, in get
  File "requests_cache\session.py", line 115, in request
  File "requests\sessions.py", line 587, in request
  File "requests_cache\session.py", line 147, in send
  File "requests_cache\session.py", line 189, in _send_and_cache
  File "requests\sessions.py", line 723, in send
  File "requests\sessions.py", line 723, in <listcomp>
  File "requests\sessions.py", line 266, in resolve_redirects
  File "requests_cache\session.py", line 147, in send
  File "requests_cache\session.py", line 189, in _send_and_cache
  File "requests\sessions.py", line 701, in send
  File "requests\adapters.py", line 547, in send
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2022-11-21 07:26:08.772|DEBUG|geventwebsocket.handler|websocket.py:368|close|Closed WebSocket
2022-11-21 07:26:08.773|DEBUG|geventwebsocket.handler|websocket.py:366|close|Failed to write closing frame -> closing socket
2022-11-21 07:26:08.773|DEBUG|geventwebsocket.handler|websocket.py:368|close|Closed WebSocket

**Comment by triwinds** [comment]
> 2022-11-21 07:25:10.583|INFO|utils.network|network.py:74|get_finial_url_with_mode|using origin url: https://api.github.com/repos/pineappleEA/pineapple-src/releases

你现在用的是直连的地址，设置里面改成使用 CDN 再试试吧

**Comment by AyanamiRei21** [comment]
> > 2022-11-21 07:25:10.583|INFO|utils.network|network.py:74|get_finial_url_with_mode|using origin url: https://api.github.com/repos/pineappleEA/pineapple-src/releases
> 
> 你现在用的是直连的地址，设置里面改成使用 CDN 再试试吧

问题解决了，非常感谢。

我没有设置里好好看过，真是抱歉。而且我最近登录GitHub都是通过hosts添加代理ip设置后登录，估计和这个也有关系吧。例如这些。

140.82.113.4                 central.github.com
140.82.113.4                 assets-cdn.github.com
151.101.1.6                  github.map.fastly.net
151.101.1.6                  github.global.ssl.fastly.net
140.82.113.4                 gist.github.com
185.199.108.153              github.io
140.82.113.4                 github.com
140.82.113.4                 api.github.com
140.82.113.4                 codeload.github.com
72.21.206.80                 github-cloud.s3.amazonaws.com
72.21.206.80                 github-com.s3.amazonaws.com
72.21.206.80                 github-production-release-asset-2e65be.s3.amazonaws.com
72.21.206.80                 github-production-user-asset-6210df.s3.amazonaws.com
72.21.206.80                 github-production-repository-file-5c1aeb.s3.amazonaws.com
185.199.108.153              githubstatus.com
140.82.114.18                github.community
140.82.113.4                 raw.github.com
