### ISSUE TITLE
解压安装失败

### ISSUE THREAD

**Issue by AkexStar** [triwinds/ns-emu-tools#78]
```
正在解压 yuzu 文件...
安装 yuzu 文件至目录...
yuzu ea [3824] 安装成功.
出现异常, Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 466, in _make_request
  File "<string>", line 3, in raise_from
  File "urllib3\connectionpool.py", line 461, in _make_request
  File "sentry_sdk\integrations\stdlib.py", line 121, in getresponse
  File "http\client.py", line 1375, in getresponse
  File "http\client.py", line 318, in begin
  File "http\client.py", line 279, in _read_status
  File "socket.py", line 705, in readinto
  File "gevent\_ssl3.py", line 567, in recv_into
  File "gevent\_ssl3.py", line 390, in read
  File "src\\gevent\\_hub_primitives.py", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src\\gevent\\_hub_primitives.py", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket
  File "src\\gevent\\_hub_primitives.py", line 313, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src\\gevent\\_hub_primitives.py", line 314, in gevent._gevent_c_hub_primitives._primitive_wait
  File "src\\gevent\\_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src\\gevent\\_hub_primitives.py", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src\\gevent\\_hub_primitives.py", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait
  File "src\\gevent\\_waiter.py", line 154, in gevent._gevent_c_waiter.Waiter.get
  File "src\\gevent\\_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_greenlet_primitives.py", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_greenlet_primitives.py", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src\\gevent\\_gevent_c_greenlet_primitives.pxd", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch
TimeoutError: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 798, in urlopen
  File "urllib3\util\retry.py", line 550, in increment
  File "urllib3\packages\six.py", line 770, in reraise
  File "urllib3\connectionpool.py", line 714, in urlopen
  File "urllib3\connectionpool.py", line 468, in _make_request
  File "urllib3\connectionpool.py", line 357, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='dn802605.us.archive.org', port=443): Read timed out. (read timeout=15)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "api\common_api.py", line 17, in get_available_firmware_infos
  File "module\firmware.py", line 112, in get_firmware_infos
  File "module\network.py", line 71, in sync_get
  File "requests_cache\session.py", line 103, in get
  File "requests_cache\session.py", line 159, in request
  File "requests\sessions.py", line 589, in request
  File "requests_cache\session.py", line 206, in send
  File "requests_cache\session.py", line 230, in _send_and_cache
  File "requests\sessions.py", line 725, in send
  File "requests\sessions.py", line 725, in <listcomp>
  File "requests\sessions.py", line 266, in resolve_redirects
  File "requests_cache\session.py", line 206, in send
  File "requests_cache\session.py", line 230, in _send_and_cache
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 532, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='dn802605.us.archive.org', port=443): Read timed out. (read timeout=15)
```

**Comment by triwinds** [comment]
这个不是安装的问题，是从 archive.org 获取固件列表的请求超时了，设置里面换个固件源就好了
