### ISSUE TITLE
启动时报错，似乎与代理有关，但我并没有开代理

### ISSUE THREAD

**Issue by Plainct** [triwinds/ns-emu-tools#85]
Traceback (most recent call last):
  File "main_devnull.py", line 11, in <module>
  File "main.py", line 85, in main
  File "main.py", line 17, in start_ui
  File "ui.py", line 68, in main
  File "ui.py", line 64, in import_api_modules
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "api\__init__.py", line 8, in <module>
  File "importlib\__init__.py", line 126, in import_module
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "api\common_api.py", line 9, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "module\firmware.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "module\downloader.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "module\network.py", line 50, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "utils\doh.py", line 30, in <module>
  File "httpx\_client.py", line 682, in __init__
  File "httpx\_client.py", line 685, in <dictcomp>
  File "httpx\_client.py", line 739, in _init_proxy_transport
  File "httpx\_transports\default.py", line 171, in __init__
ImportError: Using SOCKS proxy, but the 'socksio' package is not installed. Make sure to install httpx using `pip install httpx[socks]`.

**Comment by Plainct** [comment]
解决了，是安装的Python版本的问题
