### ISSUE TITLE
NsEmuTools打开后提示报错

### ISSUE THREAD

**Issue by lanjingling98** [triwinds/ns-emu-tools#94]
您好，请问NsEmuTools打开后提示报错
![1](https://github.com/triwinds/ns-emu-tools/assets/161037182/fbaf0a66-56cf-4694-98e8-debf73824094)
这种该怎么做？
使用NsEmuTools-console可以打开，但是下载时这样提示
开始下载 NsEmuTools-console.exe, 版本: [0.4.6]
使用 GitHub 镜像: [美国 拉斯维加斯] - 该公益加速源由 [LibraryCloud] 提供
starting aria2 daemon at port 52152
starting aria2 daemon at port 36353
出现异常, Traceback (most recent call last):
  File "api\updater_api.py", line 27, in update_net_by_tag
  File "module\updater.py", line 84, in update_self_by_tag
  File "module\updater.py", line 75, in download_net_by_tag
  File "module\downloader.py", line 119, in download
  File "module\downloader.py", line 128, in _download
  File "module\downloader.py", line 100, in init_aria2
  File "module\downloader.py", line 94, in init_aria2
  File "module\downloader.py", line 74, in _init_aria2
  File "sentry_sdk\integrations\stdlib.py", line 217, in sentry_patched_popen_init
  File "subprocess.py", line 992, in __init__
  File "subprocess.py", line 1379, in _get_handles
  File "subprocess.py", line 1137, in _get_devnull
FileNotFoundError: [Errno 2] No such file or directory: 'nul'

我该怎么办？期待解答。

**Comment by lanjingling98** [comment]
C:\Users\Administrator>echo 1 > nul
系统找不到指定的文件。

**Comment by triwinds** [comment]
你用的是魔改版的系统吧？看起来是系统里缺失了一个叫 `null.sys` 的服务

可以试试这两篇文章里面提到的办法：
https://www.jianshu.com/p/951d33b3bcd5
https://www.zhihu.com/question/263883511

实在不行就只能去安装原版系统了。

**Comment by lanjingling98** [comment]
好的  我去看看  万分感谢
