### ISSUE TITLE
yuzu 版本信息加载异常.

### ISSUE THREAD

**Issue by Jacob7179** [triwinds/ns-emu-tools#97]
正在获取固件信息...
使用 GitHub 镜像: [美国 Cloudflare CDN] - 该公益加速源由 [@mtr-static-official] 提供
开始下载固件...
starting aria2 daemon at port 40490
starting aria2 daemon at port 36571
出现异常, Traceback (most recent call last):
  File "urllib3\connection.py", line 203, in _new_conn
  File "utils\doh.py", line 181, in patched_create_connection
  File "urllib3\util\connection.py", line 85, in create_connection
  File "urllib3\util\connection.py", line 73, in create_connection
  File "gevent\_socketcommon.py", line 590, in connect
  File "gevent\_socketcommon.py", line 634, in _internal_connect
ConnectionRefusedError: [Errno 10061] [WinError 10061] No connection could be made because the target machine actively refused it.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 790, in urlopen
  File "urllib3\connectionpool.py", line 496, in _make_request
  File "urllib3\connection.py", line 395, in request
  File "http\client.py", line 1293, in endheaders
  File "http\client.py", line 1052, in _send_output
  File "http\client.py", line 990, in send
  File "urllib3\connection.py", line 243, in connect
  File "urllib3\connection.py", line 218, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x00000299AFF94D10>: Failed to establish a new connection: [Errno 10061] [WinError 10061] No connection could be made because the target machine actively refused it.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 844, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=36571): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000299AFF94D10>: Failed to establish a new connection: [Errno 10061] [WinError 10061] No connection could be made because the target machine actively refused it.'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "api\yuzu_api.py", line 78, in install_yuzu_firmware
  File "module\yuzu.py", line 121, in install_firmware_to_yuzu
  File "module\firmware.py", line 193, in install_firmware
  File "module\downloader.py", line 119, in download
  File "module\downloader.py", line 128, in _download
  File "module\downloader.py", line 100, in init_aria2
  File "module\downloader.py", line 94, in init_aria2
  File "module\downloader.py", line 85, in _init_aria2
  File "aria2p\api.py", line 686, in set_global_options
  File "aria2p\client.py", line 1378, in change_global_option
  File "aria2p\client.py", line 265, in call
  File "aria2p\client.py", line 361, in post
  File "requests\api.py", line 115, in post
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=36571): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000299AFF94D10>: Failed to establish a new connection: [Errno 10061] [WinError 10061] No connection could be made because the target machine actively refused it.'))
HTTPConnectionPool(host='127.0.0.1', port=36571): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000299AFF94D10>: Failed to establish a new connection: [Errno 10061] [WinError 10061] No connection could be made because the target machine actively refused it.'))
出现异常, Traceback (most recent call last):
  File "api\yuzu_api.py", line 99, in get_all_yuzu_release_versions
  File "repository\yuzu.py", line 15, in get_all_yuzu_release_versions
TypeError: string indices must be integers, not 'str'
yuzu 版本信息加载异常.
出现异常, Traceback (most recent call last):
  File "api\yuzu_api.py", line 99, in get_all_yuzu_release_versions
  File "repository\yuzu.py", line 15, in get_all_yuzu_release_versions
TypeError: string indices must be integers, not 'str'
yuzu 版本信息加载异常.
出现异常, Traceback (most recent call last):
  File "api\yuzu_api.py", line 99, in get_all_yuzu_release_versions
  File "repository\yuzu.py", line 15, in get_all_yuzu_release_versions
TypeError: string indices must be integers, not 'str'
yuzu 版本信息加载异常.
![屏幕截图 2024-03-05 123746](https://github.com/triwinds/ns-emu-tools/assets/70430960/1e881114-be5e-4355-9215-b487dc784978)

**Comment by Jacob7179** [comment]
启动时间: Tue Mar 05 2024 12:40:33 GMT+0800 (Singapore Standard Time)
出现异常, Traceback (most recent call last):
  File "api\yuzu_api.py", line 99, in get_all_yuzu_release_versions
  File "repository\yuzu.py", line 15, in get_all_yuzu_release_versions
TypeError: string indices must be integers, not 'str'
yuzu 版本信息加载异常.

**Comment by Jacob7179** [comment]
17.0.1 (Rebootless Update)

正在获取固件信息...
使用 GitHub 镜像: [美国 Cloudflare CDN] - 该公益加速源由 [GitMirror] 提供
开始下载固件...
starting aria2 daemon at port 26329
starting aria2 daemon at port 20981
出现异常, Traceback (most recent call last):
  File "urllib3\connection.py", line 203, in _new_conn
  File "utils\doh.py", line 181, in patched_create_connection
  File "urllib3\util\connection.py", line 85, in create_connection
  File "urllib3\util\connection.py", line 73, in create_connection
  File "gevent\_socketcommon.py", line 590, in connect
  File "gevent\_socketcommon.py", line 634, in _internal_connect
ConnectionRefusedError: [Errno 10061] [WinError 10061] No connection could be made because the target machine actively refused it.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 790, in urlopen
  File "urllib3\connectionpool.py", line 496, in _make_request
  File "urllib3\connection.py", line 395, in request
  File "http\client.py", line 1293, in endheaders
  File "http\client.py", line 1052, in _send_output
  File "http\client.py", line 990, in send
  File "urllib3\connection.py", line 243, in connect
  File "urllib3\connection.py", line 218, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000024A32E155D0>: Failed to establish a new connection: [Errno 10061] [WinError 10061] No connection could be made because the target machine actively refused it.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "requests\adapters.py", line 486, in send
  File "urllib3\connectionpool.py", line 844, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=20981): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024A32E155D0>: Failed to establish a new connection: [Errno 10061] [WinError 10061] No connection could be made because the target machine actively refused it.'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "api\yuzu_api.py", line 78, in install_yuzu_firmware
  File "module\yuzu.py", line 121, in install_firmware_to_yuzu
  File "module\firmware.py", line 193, in install_firmware
  File "module\downloader.py", line 119, in download
  File "module\downloader.py", line 128, in _download
  File "module\downloader.py", line 100, in init_aria2
  File "module\downloader.py", line 94, in init_aria2
  File "module\downloader.py", line 85, in _init_aria2
  File "aria2p\api.py", line 686, in set_global_options
  File "aria2p\client.py", line 1378, in change_global_option
  File "aria2p\client.py", line 265, in call
  File "aria2p\client.py", line 361, in post
  File "requests\api.py", line 115, in post
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 519, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=20981): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024A32E155D0>: Failed to establish a new connection: [Errno 10061] [WinError 10061] No connection could be made because the target machine actively refused it.'))
HTTPConnectionPool(host='127.0.0.1', port=20981): Max retries exceeded with url: /jsonrpc (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024A32E155D0>: Failed to establish a new connection: [Errno 10061] [WinError 10061] No connection could be made because the target machine actively refused it.'))

**Comment by Hodpel** [comment]
因为yuzu停运了啊...🤣

**Comment by Killua223** [comment]
哥们，yuzu寄了
